spring:
  application:
    name: g_74_shop
    #   вказуємо реквізити підключення до бази
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/g_74_shop
    username: postgres
    password: ${DB_PASSWORD} # <-- ств перемуну окружения (старе значення qwerty007)
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  mail:
    username: may.xata.eu@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

logging:
  file:
    name: logs/log.log
  level:
    root: info
# или    root: debug
